# Generated by Django 4.0.5 on 2022-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_category_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(to='crud.user'),
        ),
    ]
